# Generated by Django 5.2.6 on 2025-10-03 05:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aftercare_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientRevisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revisit_date", models.DateField()),
                ("expected_condition", models.TextField(blank=True)),
                ("actual_condition", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_revisits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisits",
                        to="aftercare_app.prescription",
                    ),
                ),
            ],
            options={
                "db_table": "patient_revisits",
                "ordering": ["-revisit_date"],
            },
        ),
    ]
